### ISSUE TITLE
Quake 1.5 is broken

### ISSUE THREAD

**Issue by grepwood** [DarkPlacesEngine/darkplaces#133]
I've tried DarkPlaces from the most recent commit at the time of writing this issue with these versions of Quake 1.5:
- beta patch 2
- Combat+ 5.7

The bug can be triggered by moving the mouse when we are in the game - a singleplayer, or multiplayer one. The demo played in the menu is unaffected.

Here's a GDB backtrace:
```
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:76
#1  0x00005555557265af in VM_getkeybind (prog=0x5555568e36d0 <prvm_prog_list+377168>) at ../../../prvm_cmds.c:3431
        bindmap = <optimized out>
        bind = 0x0
#2  0x00005555557560d3 in CLVM_ExecuteProgram (prog=<optimized out>, fnum=<optimized out>, errormessage=<optimized out>) at ../../../prvm_execprogram.h:726
        builtinnumber = <optimized out>
        i = <optimized out>
        dispatchtable = {0x555555757c33 <CLVM_ExecuteProgram+28499>, 0x555555759630 <CLVM_ExecuteProgram+35152>, 0x5555557595eb <CLVM_ExecuteProgram+35083>, 0x5555557599df <CLVM_ExecuteProgram+36095>, 0x5555557595aa <CLVM_ExecuteProgram+35018>, 0x555555759884 <CLVM_ExecuteProgram+35748>, 0x5555557599b4 <CLVM_ExecuteProgram+36052>, 0x555555759970 <CLVM_ExecuteProgram+35984>, 0x555555759945 <CLVM_ExecuteProgram+35941>, 0x555555759901 <CLVM_ExecuteProgram+35873>, 0x55555575943a <CLVM_ExecuteProgram+34650>, 0x5555557593c9 <CLVM_ExecuteProgram+34537>, 0x555555759690 <CLVM_ExecuteProgram+35248>, 0x55555575965b <CLVM_ExecuteProgram+35195>, 0x5555557596e8 <CLVM_ExecuteProgram+35336>, 0x55555575909f <CLVM_ExecuteProgram+33727>, 0x55555575902e <CLVM_ExecuteProgram+33614>, 0x555555758fdc <CLVM_ExecuteProgram+33532>, 0x555555758fa7 <CLVM_ExecuteProgram+33479>, 0x555555758f72 <CLVM_ExecuteProgram+33426>, 0x555555759262 <CLVM_ExecuteProgram+34178>, 0x5555557597dc <CLVM_ExecuteProgram+35580>, 0x5555557598c3 <CLVM_ExecuteProgram+35811>, 0x555555759224 <CLVM_ExecuteProgram+34116>, 0x555555759376 <CLVM_ExecuteProgram+34454>, 0x555555759170 <CLVM_ExecuteProgram+33936>, 0x5555557582b5 <CLVM_ExecuteProgram+30165>, 0x555555756207 <CLVM_ExecuteProgram+21799>, 0x5555557593c4 <CLVM_ExecuteProgram+34532>, 0x555555756207 <CLVM_ExecuteProgram+21799>, 0x55555575937b <CLVM_ExecuteProgram+34459>, 0x555555757f66 <CLVM_ExecuteProgram+29318>, 0x55555575833d <CLVM_ExecuteProgram+30301>, 0x555555758366 <CLVM_ExecuteProgram+30342>, 0x555555757f61 <CLVM_ExecuteProgram+29313>, 0x55555575626b <CLVM_ExecuteProgram+21899>, 0x55555575626b <CLVM_ExecuteProgram+21899>, 0x555555758338 <CLVM_ExecuteProgram+30296>, 0x5555557592a0 <CLVM_ExecuteProgram+34240>, 0x555555759305 <CLVM_ExecuteProgram+34341>, 0x555555758333 <CLVM_ExecuteProgram+30291>, 0x5555557561ab <CLVM_ExecuteProgram+21707>, 0x5555557561ab <CLVM_ExecuteProgram+21707>, 0x555555757c33 <CLVM_ExecuteProgram+28499>, 0x5555557597ab <CLVM_ExecuteProgram+35531>, 0x55555575974c <CLVM_ExecuteProgram+35436>, 0x55555575971d <CLVM_ExecuteProgram+35389>, 0x555555759a20 <CLVM_ExecuteProgram+36160>, 0x555555759a4f <CLVM_ExecuteProgram+36207>, 0x555555759514 <CLVM_ExecuteProgram+34868>, 0x5555557590da <CLVM_ExecuteProgram+33786>, 0x555555759489 <CLVM_ExecuteProgram+34729>, 0x555555759484 <CLVM_ExecuteProgram+34724>, 0x55555575947f <CLVM_ExecuteProgram+34719>, 0x555555755f93 <CLVM_ExecuteProgram+21171>, 0x55555575947a <CLVM_ExecuteProgram+34714>, 0x555555759475 <CLVM_ExecuteProgram+34709>, 0x55555575832e <CLVM_ExecuteProgram+30286>, 0x555555758329 <CLVM_ExecuteProgram+30281>, 0x555555755f93 <CLVM_ExecuteProgram+21171>, 0x55555575800b <CLVM_ExecuteProgram+29483>, 0x55555575948e <CLVM_ExecuteProgram+34734>, 0x5555557591e1 <CLVM_ExecuteProgram+34049>, 0x555555759a7e <CLVM_ExecuteProgram+36254>, 0x55555575984f <CLVM_ExecuteProgram+35695>, 0x55555575981a <CLVM_ExecuteProgram+35642>, 0x0 <repeats 47 times>, 0x555555757cfb <CLVM_ExecuteProgram+28699>, 0x0, 0x0, 0x5555557584f2 <CLVM_ExecuteProgram+30738>, 0x5555557585a6 <CLVM_ExecuteProgram+30918>, 0x5555557584c1 <CLVM_ExecuteProgram+30689>, 0x555555758581 <CLVM_ExecuteProgram+30881>, 0x555555758517 <CLVM_ExecuteProgram+30775>, 0x55555575854e <CLVM_ExecuteProgram+30830>, 0x555555758a01 <CLVM_ExecuteProgram+32033>, 0x5555557589e2 <CLVM_ExecuteProgram+32002>, 0x0, 0x0, 0x555555758e4e <CLVM_ExecuteProgram+33134>, 0x555555758e92 <CLVM_ExecuteProgram+33202>, 0x0, 0x0, 0x5555557589bd <CLVM_ExecuteProgram+31965>, 0x555555758998 <CLVM_ExecuteProgram+31928>, 0x55555575875d <CLVM_ExecuteProgram+31357>, 0x555555758640 <CLVM_ExecuteProgram+31072>, 0x555555758b01 <CLVM_ExecuteProgram+32289>, 0x555555758a61 <CLVM_ExecuteProgram+32129>, 0x0, 0x0, 0x555555758b2b <CLVM_ExecuteProgram+32331>, 0x555555758666 <CLVM_ExecuteProgram+31110>, 0x0 <repeats 12 times>, 0x555555757cfb <CLVM_ExecuteProgram+28699>, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5555557588a8 <CLVM_ExecuteProgram+31688>, 0x5555557588d2 <CLVM_ExecuteProgram+31730>, 0x555555758854 <CLVM_ExecuteProgram+31604>, 0x55555575887e <CLVM_ExecuteProgram+31646>, 0x555555758783 <CLVM_ExecuteProgram+31395>, 0x5555557587b9 <CLVM_ExecuteProgram+31449>, 0x555555758d15 <CLVM_ExecuteProgram+32821>, 0x555555758d4b <CLVM_ExecuteProgram+32875>, 0x555555758c32 <CLVM_ExecuteProgram+32594>, 0x555555758c65 <CLVM_ExecuteProgram+32645>, 0x555555758bc9 <CLVM_ExecuteProgram+32489>, 0x555555758bfc <CLVM_ExecuteProgram+32540>, 0x555555758ac6 <CLVM_ExecuteProgram+32230>, 0x555555758a8b <CLVM_ExecuteProgram+32171>, 0x0, 0x0, 0x0, 0x0, 0x55555575872b <CLVM_ExecuteProgram+31307>, 0x5555557586fc <CLVM_ExecuteProgram+31260>, 0x5555557586af <CLVM_ExecuteProgram+31183>, 0x0, 0x55555575860c <CLVM_ExecuteProgram+31020>, 0x5555557585d5 <CLVM_ExecuteProgram+30965>, 0x555555758971 <CLVM_ExecuteProgram+31889>, 0x55555575894a <CLVM_ExecuteProgram+31850>, 0x555555758923 <CLVM_ExecuteProgram+31811>, 0x5555557588fc <CLVM_ExecuteProgram+31772>, 0x555555758823 <CLVM_ExecuteProgram+31555>, 0x5555557587ec <CLVM_ExecuteProgram+31500>, 0x555555758cd8 <CLVM_ExecuteProgram+32760>, 0x555555758c9b <CLVM_ExecuteProgram+32699>, 0x555555758b8e <CLVM_ExecuteProgram+32430>, 0x555555758b50 <CLVM_ExecuteProgram+32368>, 0x555555758a26 <CLVM_ExecuteProgram+32070>, 0x555555758f37 <CLVM_ExecuteProgram+33367>, 0x555555758e49 <CLVM_ExecuteProgram+33129>, 0x555555758e44 <CLVM_ExecuteProgram+33124>, 0x555555758e3f <CLVM_ExecuteProgram+33119>, 0x555555756170 <CLVM_ExecuteProgram+21648>, 0x555555758dd2 <CLVM_ExecuteProgram+33010>, 0x555555756170 <CLVM_ExecuteProgram+21648>, 0x555555758dd7 <CLVM_ExecuteProgram+33015>, 0x555555758d8d <CLVM_ExecuteProgram+32941>, 0x555555758d88 <CLVM_ExecuteProgram+32936>, 0x555555758d83 <CLVM_ExecuteProgram+32931>, 0x555555758d7e <CLVM_ExecuteProgram+32926>, 0x555555756135 <CLVM_ExecuteProgram+21589>, 0x5555557582b0 <CLVM_ExecuteProgram+30160>, 0x555555756135 <CLVM_ExecuteProgram+21589>, 0x55555575811b <CLVM_ExecuteProgram+29755>, 0x0, 0x0, 0x0, 0x0, 0x555555758142 <CLVM_ExecuteProgram+29794>}
        st = <optimized out>
        startst = <optimized out>
        func = 0x5555624988b0
        enterfunc = 0x555562491370
        ed = <optimized out>
        ptr = <optimized out>
        jumpcount = 12
        cachedpr_trace = <optimized out>
        exitdepth = 0
        restorevm_tempstringsbuf_cursize = 0
        calltime = 129185.074327048
        tm = <optimized out>
        starttm = 129185.074327048
        tempfloat = <optimized out>
        cached_edictsfields = 0x55555b1ac6f0
        cached_entityfields = 211
        cached_entityfields_3 = 208
        cached_entityfieldsarea = 108032
        cached_entityfieldsarea_entityfields = 107821
        cached_entityfieldsarea_3 = 108029
        cached_entityfieldsarea_entityfields_3 = 107818
        cached_max_edicts = 512
        cached_statements = 0x555560b5c150
--Type <RET> for more, q to quit, c to continue without paging--
        cached_allowworldwrites = false
        cached_flag = 1
        globals = <optimized out>
        chooseexecprogram = <optimized out>
#3  0x0000555555672d84 in CL_VM_InputEvent (eventtype=eventtype@entry=2, x=<optimized out>, y=<optimized out>) at ../../../csprogs.c:470
        prog = <optimized out>
        r = <optimized out>
#4  0x0000555555611266 in CL_Input () at ../../../cl_input.c:546
        mx = <optimized out>
        my = <optimized out>
        old_mouse_x = 0
        old_mouse_y = 0
#5  0x000055555561b928 in CL_Frame (time=time@entry=0.0066896030039060861) at ../../../cl_main.c:2896
        clframetime = 0.0066896030039060861
        cl_timer = 0
        time1 = 0
        time2 = 0
        time3 = 0
        pass1 = <optimized out>
        pass2 = <optimized out>
        pass3 = <optimized out>
        maxfps = <optimized out>
#6  0x00005555556be80c in Host_Frame (time=0.0066896030039060861) at ../../../host.c:643
        cl_wait = <optimized out>
        sv_wait = 0.0022194823686731979
        cl_wait = <optimized out>
        sv_wait = <optimized out>
#7  Host_Main () at ../../../host.c:699
        time = 0.0066896030039060861
        oldtime = 129185.073729058
        sleeptime = <optimized out>
#8  0x00005555555ce76e in main (argc=<optimized out>, argv=<optimized out>) at ../../../sys_shared.c:1088
```

**Comment by Baker7** [comment]
I was going to report a bug with the fiend jump that causes sliding corpses in Quake 1.5

However, when I start up the autobuild 20240310, QuakeCombatPlus segfaults on Windows.

So here is a Zircon screenshot ...



![slider](https://github.com/DarkPlacesEngine/darkplaces/assets/160253/e55ea662-8bda-4c76-84dd-3fad2c338e1f)
